#!/bin/bash
myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`;

			   red='\e[1;31m'
               green='\e[0;32m'
               NC='\e[0m'
			   
               echo -e "${red}Connecting to Rasta-Server.net...${NC}"
               sleep 0.1
			   
			   echo "Connecting to your ip :$myip"
               sleep 0.3
               
			   echo "Checking Permission..."
               sleep 0.4
               
			   echo -e "${green}Permission Accepted...${NC}"
               sleep 0.5
flag=0

wget --quiet -O ip.txt https://raw.githubusercontent.com/rasta-team/SERVER_IP_REGISTER/master/ip.txt

echo "" 
echo "        ---------[WELCOME TO RASTA-TEAM™ AUTO-SCRIPT]----------"
echo "        ====================================================="
echo "        #           WhatsApp     : +60169872312             #"
echo "        #           Telegram     : @myvpn007                #"
echo "        #                                                   #"
echo "        #       Copyright: © RASTA-TEAM™ Premium 2018       #"
echo "        ====================================================="
echo ""

#read -p "Your IP Server: " -e -i $myip
echo ""

echo "Checking Permission..."
sleep 1

ip="ip.txt"


lines=`cat $ip`

for line in $lines; do

        if [ "$line" = "$myip" ];
        then
                flag=1
				echo ""
				echo -e "${green}Permission Accepted...${NC}"
				sleep 0.5
				echo ""
				echo "		==============================		"
				echo "		Thanks for using our services.		"
				echo "		==============================		"
				echo ""
        fi
		
done

if [ $flag -eq 0 ]
then
clear
echo "                                                        				 "
echo "======================================================================="
echo  "Sorry, your ip address $myip is not allowed to access this scripts"
echo "                                                        "
echo "Please contact your network administrator to access this service.
IT-Department : +0169872312
Telegram : @myvpn007"
echo "======================================================================="

rm -f /root/ip.txt

	exit 1
fi

function create_user() {
#myip=`dig +short myip.opendns.com @resolver1.opendns.com`
#clear
echo -e ""
echo -e ""
echo -e ""
echo -e ""
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $uname
exp="$(chage -l $uname | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$pass\n$pass\n"|passwd $uname &> /dev/null
echo -e ""
echo -e "|      Account Information for $myip      |"
echo -e "============-RASTA-TEAM™-================" 
echo -e "     Host: $myip"
echo -e "     Username: $uname" 
echo -e "     Password: $pass                     " 
echo -e "     Port default dropbear: 443          " 
echo -e "     Port default openSSH : 22           " 
echo -e "     Port default squid   : 80, 3128, 8080         " 
echo -e "     Port default openVPN : 1194           " 
echo -e "     Auto kill user maximal login 1      "
echo -e "-----------------------------------------"
echo -e "     Aktif Sampai: $exp                  " 
echo -e "=========================================" 
echo -e "   DI LARANG:                            "
echo -e "   HACKING-DDOS-PHISING-SPAM-TORENT      " 
echo -e "   CARDING-CRIMINAL CYBER.               "
echo -e "===========================================" 
echo -e "   Script by RASTA-TEAM™                 "
myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
echo -e "   Config OVPN:                          "
echo -e "   http://$myip:81/1194-client.ovpn      " 
echo -e "-----------------------------------------" 
echo -e ""
echo -e ""
}
function renew_user() {
	echo "Tamat Tempoh User: $uname Di Perbarui Sampai: $expdate";
	usermod -e $expdate $uname
}

function delete_user(){
	
	userdel $uname
}

function expired_users(){
echo "                      _\|/_      "
echo "                      (o o)      "
echo "-------------------o00-{_}-00o---"
echo "BIL  USERNAME          EXPIRED "
echo "---------------------------------"
count=1
	cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
	totalaccounts=`cat /tmp/expirelist.txt | wc -l`
	for((i=1; i<=$totalaccounts; i++ )); do
	tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
		username=`echo $tuserval | cut -f1 -d:`
		userexp=`echo $tuserval | cut -f2 -d:`
		userexpireinseconds=$(( $userexp * 86400 ))
		todaystime=`date +%s`
		expired="$(chage -l $username | grep "Account expires" | awk -F": " '{print $2}')"
		if [ $userexpireinseconds -lt $todaystime ] ; then
			printf "%-4s %-15s %-10s %-3s\n" "$count." "$username" "$expired"
			count=$((count+1))
		fi
	done
	rm /tmp/expirelist.txt
}

function not_expired_users(){
    cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
    totalaccounts=`cat /tmp/expirelist.txt | wc -l`
    for((i=1; i<=$totalaccounts; i++ )); do
        tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
        username=`echo $tuserval | cut -f1 -d:`
        userexp=`echo $tuserval | cut -f2 -d:`
        userexpireinseconds=$(( $userexp * 86400 ))
        todaystime=`date +%s`
        if [ $userexpireinseconds -gt $todaystime ] ; then
            echo $username
        fi
    done
	rm /tmp/expirelist.txt
}

function monssh2(){
echo ""
echo "|   Tgl-Jam    | PID   |   User Name  |      Dari IP      |"
echo "-------------------------------------------------------------"
data=( `ps aux | grep -i dropbear | awk '{print $2}'`);

echo "=================[ Checking Dropbear login ]================="
echo "-------------------------------------------------------------"
for PID in "${data[@]}"
do
	#echo "check $PID";
	NUM=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | wc -l`;
	USER=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | awk -F" " '{print $10}'`;
	IP=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | awk -F" " '{print $12}'`;
	waktu=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | awk -F" " '{print $1,$2,$3}'`;
	if [ $NUM -eq 1 ]; then
		echo "$waktu - $PID - $USER - $IP";
	fi
done


echo "-------------------------------------------------------------"
data=( `ps aux | grep "\[priv\]" | sort -k 72 | awk '{print $2}'`);

echo "==================[ Checking OpenSSH login ]================="
echo "-------------------------------------------------------------"
for PID in "${data[@]}"
do
        #echo "check $PID";
		NUM=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | wc -l`;
		USER=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | awk '{print $9}'`;
		IP=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | awk '{print $11}'`;
		waktu=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | awk '{print $1,$2,$3}'`;
        if [ $NUM -eq 1 ]; then
                echo "$waktu - $PID - $USER - $IP";
        fi
done

echo "-------------------------------------------------------------"
echo -e "==============[ User Monitor Dropbear & OpenSSH]============="
}

function used_data(){
	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`
	myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`
	ifconfig $myint | grep "RX bytes" | sed -e 's/ *RX [a-z:0-9]*/Received: /g' | sed -e 's/TX [a-z:0-9]*/\nTransfered: /g'
}

function bench-network2(){
wget freevps.us/downloads/bench.sh -O - -o /dev/null|bash
echo -e "Sekian...!!!"
}

function user_list(){
echo "---------------------------------------------"
echo "BIL  USERNAME        STATUS       EXP DATE   "
echo "---------------------------------------------"
C=1
ON=0
OFF=0
while read mumetndase
do
        AKUN="$(echo $mumetndase | cut -d: -f1)"
        ID="$(echo $mumetndase | grep -v nobody | cut -d: -f3)"
        exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
        online="$(cat /etc/openvpn/openvpn-status.log | grep -Eom 1 $AKUN | grep -Eom 1 $AKUN)"
        if [[ $ID -ge 500 ]]; then
        if [[ -z $online ]]; then
        printf "%-4s %-15s %-10s %-3s\n" "$C." "$AKUN" "OFFLINE" "$exp"
        OFF=$((OFF+1))
        else
        printf "%-4s %-15s %-10s %-3s\n" "$C." "$AKUN" "ONLINE" "$exp"
        ON=$((ON+1))
        fi
        C=$((C+1))
        fi
JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
done < /etc/passwd
echo "--------------------------------------------------"
echo " TOTAL USER : $JUMLAH    ONLINE : $ON     OFFLINE : $OFF"
echo "--------------------------------------------------"
}

function lokasi(){

data=( `ps aux | grep -i dropbear | awk '{print $2}'`);

echo "User Login"
echo "=================================";
echo "Dropbear" 
for PID in "${data[@]}"
do
    #echo "check $PID";
    NUM=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | wc -l`;
    USER=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | awk '{print $10}'`;
    IP=`cat /var/log/auth.log | grep -i dropbear | grep -i "Password auth succeeded" | grep "dropbear\[$PID\]" | awk '{print $12}'`;
    if [ $NUM -eq 1 ]; then
        echo "$USER - $IP";
    fi
done
echo ""
echo "OpenSSH";

data=( `ps aux | grep "\[priv\]" | sort -k 72 | awk '{print $2}'`);


for PID in "${data[@]}"
do
        #echo "check $PID";
        NUM=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | wc -l`;
        USER=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | awk '{print $9}'`;
        IP=`cat /var/log/auth.log | grep -i sshd | grep -i "Accepted password for" | grep "sshd\[$PID\]" | awk '{print $11}'`;
        if [ $NUM -eq 1 ]; then
                echo "$USER - $IP";
        fi
done
echo "-------------------------------" 
}


rm -f /root/ip.txt
clear
echo ""
echo ""
echo "" 
clear

echo "---------[WELCOME TO RASTA-TEAM™ AUTO-SCRIPT]---------- 
WhatsApp     : +60169872312
Telegram     : @myvpn007
Copyright: © RASTA-TEAM™ Premium 2018 
 " 
echo "System by Rasta Team"

echo ""
PS3='Silahkan ketik nomor pilihan anda lalu tekan ENTER: '
options=("Buat User" "Renew User" "Delete User" "Delete User Expired" "Monitor User" "User Detail" "User List" "Auto-Limit" "Log Limit" "Auto-Kill User" "Ban User" "Un-Ban User" "Log Ban" "Speed Test" "Restart All Port" "Set Auto Reboot" "Bersihkan cache ram" "Quit")
select opt in "${options[@]}"
do
    case $opt in
	
    "Buat User")
    clear
	read -p "Enter username: " uname
    read -p "Enter password: " pass
	read -p "Tamat Tempoh (Berapa Hari): " masaaktif
	#read -p "Aktif sampai tanggal Thn-Bln-Hr(YYYY-MM-DD): " expdate
	
	echo "Connecting to rasta-team.net..."
	sleep 0.4
	echo "Creating Account..."
	sleep 0.3
	echo "Generating Host..."
	sleep 0.2
	echo "Creating Your New Username: $uname"
	sleep 0.2
	echo "Creating Password for $uname"
	sleep 1
	#masaaktif="30"
    #read -p "Tamat Tempoh (Berapa Hari): " masaaktif
    #clear
    create_user
	break
    #buatakun
	#break
    ;;
	
	"Renew User")
	clear
	user-list
	read -p "Enter username yg di perbarui: " uname
	#masaaktif="30"
	read -p "Tamat Tempoh (Berapa Hari): " masaaktif
    #read -p "Aktif sampai tanggal Thn-Bln-Hr(YYYY-MM-DD): " expdate
	
	echo "Connecting to rasta-team.net..."
	sleep 0.4
	echo "Creating Account..."
	sleep 0.3
	echo "Generating Host..."
	sleep 0.2
	echo "Renew Your Username: $uname"
	sleep 0.2
    renew_user
    break
	#userrenew
	#break
	;;
	
    "Delete User")
	user-list
	echo ""
    read -p "Ketik user (di atas) yang akan di hapus: " uname 
	echo -e "${red}Connecting to rasta-server.net...${NC}"
               sleep 0.5
			   
			   echo "Connecting to your ip : $myip ...."
               sleep 1
               
			   echo "Checking Permission..."
               sleep 1
               
			   echo -e "${green}Permission Accepted...${NC}"
               sleep 0.5

			   echo -e "User $uname sukses dihapus boss!!!"
    delete_user
    break
    ;;
	
	"Delete User Expired")
	deleteuserexpire
	break
	;;
	
    "Monitor User")
	monssh2
	#userlogin
	break
    ;;
	
	"User Detail")
	userdetail
	break
	;;
	
	"User List")
	user-list
    break
	;;
	
	"Auto-Limit")
	autolimit
	break
	;;
	
	"Log Limit")
	loglimit
	break
	;;

	"Auto-Kill User")
	autokilluser
	break
	;;		
	
	"Ban User")
	userban
	break
	;;
		
	"Un-Ban User")
	userunban
	break
	;;
		
	"Log Ban")
	logban
	break
	;;
	
	"Speed Test")
	echo""
    echo "Speed Test Server"
    ./speedtest.py --share
    echo "Hasil Speed test diatas Script by Rasta-Team.net"
 	break
	;;
		
	"Restart All Port")
	clear
	echo "Service Openvpn restart .................tunggu sebentar"
	service openvpn restart
	echo "Restart OpenVPN selesai Script By Rasta-Team.net"
	sleep 0.5

	
	echo "Service Dropbear restart .................tunggu sebentar"
	service dropbear restart
	echo "Restart Dropbear selesai Script By Rasta-Team.net"
	sleep 0.5
	
	echo "Service Squid restart .................tunggu sebentar"
	service squid3 restart
	echo "Restart Squid selesai Script By Rasta-Team.net"
	sleep 0.5
	
	echo "Service Webmin restart .................tunggu sebentar"
	/etc/init.d/webmin restart
	echo "Restart Webmin selesai Script By Rasta-Team.net"
	
	break
	;;
	
	"Set Auto Reboot")
	autoreboot
	break
	;;
	
	"Bersihkan cache ram")
	echo 3 > /proc/sys/vm/drop_caches && swapoff -a && swapon -a
	echo "SUKSES..!!!Cache ram anda sudah di bersihkan."
	break
	;;
	
	"Quit")
	red='\e[1;31m'
    green='\e[0;32m'
    NC='\e[0m'
			   
    echo -e "${red}Bye...Bye....${NC}"
    sleep 0.5	
	break
	;;
	 
    *) echo invalid option;
	esac
done